---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: API_KEY
    value: ${API_KEY}
    type: secure
  - name: PROD_ORG_NAME
    value: ${PROD_ORG_NAME}
    type: text
  - name: PROD_SPACE_NAME
    value: ${PROD_SPACE_NAME}
    type: text
  - name: CF_APP
    value: ${CF_APP_NAME}
    type: text
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
          echo ">>> Logging into IBM Cloud…"
          echo $PROD_SPACE_NAME
          echo $PROD_ORG_NAME
          bx login --apikey $API_KEY -a api.ng.bluemix.net -o "$PROD_ORG_NAME" -s "$PROD_SPACE_NAME"
          echo ">>> Currently Deployed Packages:"
          bx wsk package list
          echo ">>> Currently Deployed Actions:"
          bx wsk action list
          echo ">>> Currently Deployed Triggers:"
          bx wsk trigger list
          echo ">>> Currently Deployed Rules:"
          bx wsk rule list
          echo ">>> Lista de archivos…"
          ls -lh
          echo ">>> Deploying…"
          bx wsk action update $CF_APP main.js --kind nodejs:8 --web true --param-file params.json
