---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: API_KEY
    value: ${API_KEY}
    type: secure
  - name: PROD_ORG_NAME
    value: ${PROD_ORG_NAME}
    type: text
  - name: PROD_SPACE_NAME
    value: ${PROD_SPACE_NAME}
    type: text
  jobs:
  - name: Build
    type: builder
    build_type: npm
