---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: API_KEY
    value: ${API_KEY}
    type: secure
  - name: PROD_ORG_NAME
    value: ${PROD_ORG_NAME}
    type: text
  - name: PROD_SPACE_NAME
    value: ${PROD_SPACE_NAME}
    type: text
  jobs:
  - name: Build
    type: builder
    build_type: npm
    script: |
    #!/bin/bash
    # The default Node.js version is 0.10.40
    # To use Node.js 0.10.48, uncomment the following line:
    #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
    # To use Node.js 0.12.7, uncomment the following line:
    #export PATH=/opt/IBM/node-v0.12/bin:$PATH
    # To use Node.js 4.4.5, uncomment the following line:
    #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
    # To use Node.js 6.7.0, uncomment the following line:
    export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
    npm install
    ls -lh

    #!/bin/bash
    echo ">>> Lista de archivos…"
    #ls -lh
    echo ">>> Hace el .zip…"
    zip -r action.zip main.js package* node_modules
    echo ">>> Lista de archivos…"
    ls -lh
    echo ">>> Checking installed version of IBM Cloud CLI…"
    bx help
    echo ">>> Logging into IBM Cloud…"
    echo $API_KEY
    echo $PROD_SPACE_NAME
    echo $PROD_ORG_NAME
    bx login –apikey $API_KEY -a api.ng.bluemix.net -o "$PROD_ORG_NAME" -s "$PROD_SPACE_NAME"

    echo ">>> Currently Deployed Packages:"
    bx wsk package list
    echo ">>> Currently Deployed Actions:"
    bx wsk action list
    echo ">>> Currently Deployed Triggers:"
    bx wsk trigger list
    echo ">>> Currently Deployed Rules:"
    bx wsk rule list
    echo ">>> Deploying Actions Using WhiskDeploy…"
    bx wsk action update fb-watson action.zip --kind nodejs:6 --web true --param-file params.json
    echo ">>> Successfully Deployed Actions."
